import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from .base import BaseNotifier
from src.utils.config import settings

logger = logging.getLogger(__name__)

class EmailNotifier(BaseNotifier):
    """
    Notifier for Email using SMTP.
    """
    def __init__(self):
        # Validate required settings
        if not (settings.SMTP_HOST and settings.SMTP_PORT and settings.SMTP_USER and settings.SMTP_PASS):
             logger.warning("SMTP settings are incomplete. Email notifications will fail.")
             self.ready = False
        else:
             self.ready = True

    def send(self, title: str, message: str, url: str, category: str = "General") -> bool:
        if not self.ready:
            logger.error("Cannot send Email: SMTP settings incomplete.")
            return False

        msg = MIMEMultipart()
        msg['From'] = settings.SMTP_USER
        msg['To'] = settings.SMTP_USER # Send to self/admin for now, or add RECIPIENT config later
        msg['Subject'] = f"AWS-Brief: [{category}] {title}"

        body = f"""
        <html>
          <body>
            <h2>[{category}] {title}</h2>
            <p><strong>Summary:</strong></p>
            <p>{message}</p>
            <br>
            <p><a href="{url}" style="background-color: #FF9900; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">Read full story on AWS</a></p>
            <hr>
            <small>Generated by AWS-Brief AI</small>
          </body>
        </html>
        """
        msg.attach(MIMEText(body, 'html'))

        try:
            # Connect to SMTP Server
            server = smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT)
            server.starttls() # Secure the connection
            server.login(settings.SMTP_USER, settings.SMTP_PASS.get_secret_value())
            
            server.sendmail(settings.SMTP_USER, settings.SMTP_USER, msg.as_string())
            server.quit()
            
            logger.info(f"Email sent for: {title}")
            return True
        except Exception as e:
            logger.error(f"Failed to send Email: {e}")
            return False
